# Generated by Django 4.2.5 on 2023-09-25 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigation',
            name='page_type',
            field=models.CharField(blank=True, choices=[('Home', 'Home'), ('Aboutus', 'Aboutus'), ('Portfolio', 'Portfolio'), ('Profile', 'Profile'), ('Service', 'Service'), ('ServiceData', 'ServiceData'), ('Aboutus', 'Aboutus'), ('Banner', 'Banner'), ('Recent Project', 'Recent Project'), ('Upcoming Project', 'Upcoming Project'), ('Past Program', 'Past Program'), ('News', 'News'), ('Vision', 'Vision'), ('Message', 'Message'), ('About Indreni', 'About Indreni'), ('Guideline Principles', 'Guideline Principle'), ('Organizational Process', 'Organizational Process'), ('Our Histroy', 'Our Histroy'), ('Our Mision', 'Our Mision'), ('Services', 'Services'), ('Side Notice', 'Side Notice'), ('Uniqueness Indreni', 'Uniqueness Indreni'), ('BannerData', 'BannerData'), ('CourseHome', 'CourseHome'), ('LatestNews', 'LatestNews'), ('LatestNewsData', 'LatestNewsData'), ('ServiceHome', 'ServiceHome'), ('ServiceHomeData', 'ServiceHomeData'), ('Testimonial', 'Testimonial'), ('TestimonialData', 'TestimonialData'), ('DailyRashifal', 'DailyRashifal'), ('WeeklyRashifal', 'WeeklyRashifal'), ('MonthlyRashifal', 'MonthlyRashifal'), ('YearlyRashifal', 'YearlyRashifal'), ('DailyRashifalHome', 'DailyRashifalHome'), ('WeeklyRashifalHome', 'WeeklyRashifalHome'), ('MonthlyRashifalHomeHome', 'MonthlyRashifalHomeHome'), ('YearlyRashifal', 'YearlyRashifal'), ('Group', 'Group'), ('Contact', 'Contact'), ('SarbeswarJyotish', 'SarbeswarJyotish'), ('MahadevJyotish', 'MahadevJyotish'), ('HariJyotish', 'HariJyotish'), ('PashupatiJyotish', 'PashupatiJyotish'), ('GuruJyotish', 'GuruJyotish'), ('OmJyotish', 'OmJyotish'), ('Photo', 'Photo'), ('PhotoData', 'PhotoData'), ('Video', 'Video'), ('VideoData', 'VideoData')], max_length=50, null=True),
        ),
    ]
